spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true

springdoc:
  api-docs:
    path: /open-api.json
    enabled: false
  swagger-ui:
    path: /swagger-ui.html
    enabled: false
  packages-to-scan: org.ducanh.apiiam.controllers
  show-actuator: false

app:
  exceptions-handle:
    log-stack-trace: true
