spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ducanh
    username: ducanh
    password: ducanh
    hikari:
      schema: public
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password:
      timeout: 6000
      username:
springdoc:
  api-docs:
    path: /open-api.json
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: org.ducanh.apiiam.controllers
  show-actuator: true

logging:
  level:
    com.zaxxer.hikari: DEBUG
    com.zaxxer.hikari.HikariConfig: TRACE
  config: classpath:log4j2-local.xml

app:
  exceptions-handle:
    log-error-detail: true
