spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    clean-disabled: false

springdoc:
  api-docs:
    path: /open-api.json
    enabled: false
  swagger-ui:
    path: /swagger-ui.html
    enabled: false
  packages-to-scan: org.ducanh.apiiam.controllers
  show-actuator: false

logging:
  level:
    org.springframework.data.redis: debug
    io.lettuce.core: debug

app:
  exceptions-handle:
    log-error-detail: true
