spring:
  application:
    name: api-iam
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/}
    username: ${DATABASE_USERNAME:username}
    password: ${DATABASE_PASSWORD:password}
    hikari:
      connection-timeout: ${HIKARI_CONNECTION_TIMEOUT:30000}
      maximum-pool-size: ${HIKARI_MAX_POOL_SZ:20}
      minimum-idle: ${HIKARI_MIN_IDLE:5}
      idle-timeout: ${HIKARI_IDE_TIMEOUT:30000}
      max-lifetime: ${HIKARI_MAX_LIFETIME:120000}
      # Config for check connection alive.
      connection-test-query: SELECT 1
      validation-timeout: 3000
      pool-name: "DefaultHikariPool"

app:
  auth:
    max-user-active-session: ${MAX_ACTIVE_SESSION:5}
  exception:
    debug: false
server:
  port: ${SERVER_PORT:8001}